### PR TITLE
Make history file separator configurable

### PR DESCRIPTION
**Pull request by peskdale**
Completes feature request #65 

Allows user to use whatever delimiter they want for the history file. Defaults to semi-colon.

### CODE REVIEW

**Comment by peskdale** [comment]
First two changes made.

Regarding the position in the config, it has to be positioned before POST_HISTORY. Otherwise, the file will get created with the default separator. However, I have now given it it's own comment.

**Comment by mbruel** [comment]
it makes more sense to have FIELD_SEPARATOR after POST_HISTORY as it concerns it...
even with its own comment. Please move it under. the position won't affect anything.

what about my first point? your test is always true...

**Comment by peskdale** [comment]
I have tested, and the position does make a difference. If the history file needs to be created, it does not use the configured separator unless it is defined first. The config file options are evaluated in the order they appear, meaning [this code](https://github.com/peskdale/ngPost/blob/master/src/NgPost.cpp#L1795) will be run, using the default separator, if POST_HISTORY appears before FIELD_SEPARATOR can change it.

Regardinf your first point, I already replaced the test with the code you suggested.

**Comment by mbruel** [comment]
hum I see...
well then you need to change that code, it's not right. I've done it on the main branch.
so please update and put FIELD_SEPARATOR under POST_HISTORY

**Comment by peskdale** [comment]
That should be better now

**Comment by mbruel** [comment]
how can I see the diff of your branch and the master? (latest changes)

**Comment by peskdale** [comment]
Diff can be found by clicking "Files changed" at the top of this page...

...or using this link: https://github.com/mbruel/ngPost/pull/66/files

**Comment by mbruel** [comment]
ok thanks, all good, it's on the master branch ;)

**Pull request merged**
