### PR TITLE
Add Dockerfile and other improvements

### PR DESCRIPTION
**Pull request by pankkake**
Since I can't compile it easily on my headless server (installing qtqui requires installing a lot of things, even on Gentoo) I made a Docker image.

One future improvement could be installing something like parpar in addition to par2cmdline.

### CODE REVIEW

**Comment by mbruel** [comment]
> Since I can't compile it easily on my headless server (installing qtqui requires installing a lot of things, even on Gentoo) I made a Docker image.

why don't you use the AppImage? well if you prefer docker why not... looong time I didn't use it.
you should defintely add ParPar to the docker (install nodejs and npm via apt, then clone the repo, you can use the js directly, that's what I'm doing on my machine.

I'll probably embedded a compiled version of ParPar for the next version. It will be provided in the Windows setup, in the dmg for Mac, and in the AppImage for Linux

**Comment by mbruel** [comment]
PS: at one point if I motivate myself or/and get some help, I may try to release a deb file and try to get into Debian / Ubuntu repos... Could be cool :)

**Comment by pankkake** [comment]
I didn't try the AppImage, mostly because I'm a paranoid Gentoo user and don't like running untrusted binaries ;-)
Also, I'm not sure it would have ran without the Qt libs and X libs installed (depends on how it was compiled statically I guess).
However, I could have ran the AppImage in docker.

**Comment by mbruel** [comment]
you're not allowed to compile statically with Qt opensource licence. So I didn't. The goal of the appImage is like a small docker: to embedded all the required libs needed for the execution of the app.
You can extract the AppImage...
If you're paranoid, you can compile ngPost from the source on another computer (Linux x64) and change the one I've put.. but believe, I didn't add any backdoor, it's just the compiled sources! lol

**Comment by mbruel** [comment]
yeah, so if you don't want to compile on an headless station, even if I don't get the principle... (no need to install any graphical stacks, headers are safe and not heavy)
you can compile yourself and build an AppImage. I guess it is less constraining than using docker ;)

**Pull request merged**
